apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniqwear-ingress
  namespace: uniqwear
  annotations:
    # nginx-ingress jest domyslnym kontrolerem dla kind/minikube/k3d
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: uniqwear.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 3000
