apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../namespace.yaml
- ../configmap.yaml
- ../secret.yaml
- ../pvc.yaml
- ../postgres-statefulset.yaml
- ../mongo-statefulset.yaml
- ../redis-statefulset.yaml
- ../services.yaml
- ../catalog-deployment.yaml
- ../checkout-deployment.yaml
- ../gateway-deployment.yaml
- ../ingress.yaml
- ../networkpolicy.yaml
- ../pdb.yaml
